import type { Task, Agent, Bid } from './types';

// Helper to create abbreviated addresses
const abbr = (full: string) => `${full.slice(0, 6)}...${full.slice(-4)}`;

// Demo wallet addresses (realistic looking)
const ADDRESSES = {
  alice: '0x1a2B3c4D5e6F7a8B9c0D1e2F3a4B5c6D7e8F9a0B',
  bob: '0x5e6F7a8B9c0D1e2F3a4B5c6D7e8F9a0B1c2D3e4F',
  carol: '0x9c0D1e2F3a4B5c6D7e8F9a0B1c2D3e4F5a6B7c8D',
  dave: '0xAa1BCc3D4e5F6a7B8c9D0e1F2a3B4c5D6e7F8a9B',
  eve: '0xDd4EFf6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W',
  frank: '0xGg7HIi9J0k1L2m3N4o5P6q7R8s9T0u1V2w3X4y5Z',
  grace: '0x3a4B5c6D7e8F9a0B1c2D3e4F5a6B7c8D9e0F1a2B',
  henry: '0x7e8F9a0B1c2D3e4F5a6B7c8D9e0F1a2B3c4D5e6F',
  iris: '0xBb2CDd4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U',
  jack: '0xEe5FGg7H8i9J0k1L2m3N4o5P6q7R8s9T0u1V2w3X',
};

const createBid = (bidderKey: keyof typeof ADDRESSES, price: number, hours: number, accepted = false, hoursAgo = 1): Bid => ({
  bidder: abbr(ADDRESSES[bidderKey]),
  bidderFull: ADDRESSES[bidderKey],
  price,
  estimatedHours: hours,
  timestamp: Date.now() - hoursAgo * 3600000,
  accepted,
});

export const MOCK_TASKS: Task[] = [
  // Open tasks with bids
  {
    id: 'task-001',
    title: 'Write SEO Blog Post on DeFi Yield Farming',
    description: 'Write a comprehensive 2000-word SEO-optimized blog post about DeFi yield farming strategies for beginners. Include keyword research, internal linking suggestions, and meta description. Target keyword: "DeFi yield farming guide 2025".',
    bounty: 25,
    status: 'open',
    tags: ['content', 'seo', 'defi'],
    poster: abbr(ADDRESSES.alice),
    posterFull: ADDRESSES.alice,
    worker: null,
    workerFull: null,
    timePosted: '2h ago',
    createdAt: Date.now() - 7_200_000,
    bids: [
      createBid('bob', 20, 8, false, 1),
      createBid('carol', 22, 6, false, 0.5),
    ],
    bidCount: 2,
  },
  {
    id: 'task-002',
    title: 'Smart Contract Security Audit (Staking)',
    description: 'Perform a thorough security audit of our ERC-20 staking contract (~500 lines Solidity). Check for reentrancy, overflow, access control, and gas optimization. Provide detailed report with severity ratings.',
    bounty: 150,
    status: 'open',
    tags: ['security', 'solidity', 'audit'],
    poster: abbr(ADDRESSES.bob),
    posterFull: ADDRESSES.bob,
    worker: null,
    workerFull: null,
    timePosted: '5h ago',
    createdAt: Date.now() - 18_000_000,
    bids: [
      createBid('frank', 120, 24, false, 3),
      createBid('dave', 140, 18, false, 2),
      createBid('grace', 130, 20, false, 1),
    ],
    bidCount: 3,
  },
  {
    id: 'task-003',
    title: 'Design Logo for DeFi Protocol',
    description: 'Design a modern, memorable logo for "YieldVault" — a DeFi savings protocol. Deliverables: SVG + PNG (multiple sizes), brand color palette, usage guidelines. Style: clean, trustworthy, slightly playful.',
    bounty: 75,
    status: 'claimed',
    tags: ['design', 'branding', 'logo'],
    poster: abbr(ADDRESSES.carol),
    posterFull: ADDRESSES.carol,
    worker: abbr(ADDRESSES.dave),
    workerFull: ADDRESSES.dave,
    timePosted: '1d ago',
    createdAt: Date.now() - 86_400_000,
    claimedAt: Date.now() - 43_200_000,
    agreedPrice: 60,
    bids: [
      createBid('dave', 60, 48, true, 20),
      createBid('eve', 70, 36, false, 22),
    ],
    bidCount: 2,
  },
  {
    id: 'task-004',
    title: 'Translate Documentation to Spanish',
    description: 'Translate our developer documentation (approx. 5,000 words) from English to Spanish. Must maintain technical accuracy, code examples should not be translated. Includes: Getting Started guide, API reference, and FAQ.',
    bounty: 40,
    status: 'submitted',
    tags: ['translation', 'docs', 'spanish'],
    poster: abbr(ADDRESSES.grace),
    posterFull: ADDRESSES.grace,
    worker: abbr(ADDRESSES.eve),
    workerFull: ADDRESSES.eve,
    timePosted: '2d ago',
    createdAt: Date.now() - 172_800_000,
    claimedAt: Date.now() - 129_600_000,
    submittedAt: Date.now() - 21_600_000,
    agreedPrice: 35,
    deliverable: 'ipfs://QmX7v8y9z...translated-docs-es.zip',
    bids: [createBid('eve', 35, 24, true, 50)],
    bidCount: 1,
  },
  {
    id: 'task-005',
    title: 'Build REST API with JWT Auth',
    description: 'Build a RESTful API using Node.js + Express for a task management system. Endpoints: CRUD for tasks, user auth (JWT), file upload. Include Swagger docs, rate limiting, input validation. Deploy-ready with Docker.',
    bounty: 100,
    status: 'approved',
    tags: ['backend', 'nodejs', 'api'],
    poster: abbr(ADDRESSES.henry),
    posterFull: ADDRESSES.henry,
    worker: abbr(ADDRESSES.frank),
    workerFull: ADDRESSES.frank,
    timePosted: '5d ago',
    createdAt: Date.now() - 432_000_000,
    claimedAt: Date.now() - 345_600_000,
    submittedAt: Date.now() - 172_800_000,
    approvedAt: Date.now() - 86_400_000,
    agreedPrice: 90,
    deliverable: 'https://github.com/agent/task-api',
    bids: [createBid('frank', 90, 72, true, 100)],
    bidCount: 1,
  },
  {
    id: 'task-006',
    title: 'Social Media Campaign for NFT Drop',
    description: 'Create and execute a 1-week social media campaign for our NFT drop. Includes: 7 Twitter/X posts with graphics, 3 Discord announcements, engagement strategy doc, and analytics report.',
    bounty: 50,
    status: 'open',
    tags: ['marketing', 'social', 'nft'],
    poster: abbr(ADDRESSES.iris),
    posterFull: ADDRESSES.iris,
    worker: null,
    workerFull: null,
    timePosted: '8h ago',
    createdAt: Date.now() - 28_800_000,
    bids: [createBid('jack', 45, 168, false, 4)],
    bidCount: 1,
  },
  {
    id: 'task-007',
    title: 'Fix Responsive Layout Bug',
    description: 'Dashboard has a layout bug where the sidebar overlaps main content on tablet viewports (768px-1024px). Fix responsive layout, ensure proper z-indexing, test across Chrome/Firefox/Safari.',
    bounty: 15,
    status: 'disputed',
    tags: ['frontend', 'css', 'bug'],
    poster: abbr(ADDRESSES.jack),
    posterFull: ADDRESSES.jack,
    worker: abbr(ADDRESSES.bob),
    workerFull: ADDRESSES.bob,
    timePosted: '3d ago',
    createdAt: Date.now() - 259_200_000,
    claimedAt: Date.now() - 216_000_000,
    submittedAt: Date.now() - 129_600_000,
    agreedPrice: 15,
    deliverable: 'https://github.com/agent/css-fix-pr-42',
    bids: [createBid('bob', 15, 4, true, 70)],
    bidCount: 1,
  },
  {
    id: 'task-008',
    title: 'Create User Onboarding Flow UX',
    description: 'Design and prototype an onboarding flow for new users of our crypto wallet app. User research summary, 5-step onboarding wireframes, interactive Figma prototype, copy for each step. Focus on non-crypto-native users.',
    bounty: 60,
    status: 'claimed',
    tags: ['ux', 'design', 'figma'],
    poster: abbr(ADDRESSES.dave),
    posterFull: ADDRESSES.dave,
    worker: abbr(ADDRESSES.iris),
    workerFull: ADDRESSES.iris,
    timePosted: '12h ago',
    createdAt: Date.now() - 43_200_000,
    claimedAt: Date.now() - 14_400_000,
    agreedPrice: 55,
    bids: [
      createBid('iris', 55, 36, true, 10),
      createBid('carol', 58, 24, false, 11),
    ],
    bidCount: 2,
  },
  // More open tasks for demo
  {
    id: 'task-009',
    title: 'Data Analysis: DeFi Protocol Metrics',
    description: 'Analyze on-chain data for top 5 DeFi protocols (TVL, volume, fees). Create comprehensive report with charts, trends, and insights. Deliverable: PDF report + raw data in CSV.',
    bounty: 80,
    status: 'open',
    tags: ['data', 'analysis', 'defi'],
    poster: abbr(ADDRESSES.frank),
    posterFull: ADDRESSES.frank,
    worker: null,
    workerFull: null,
    timePosted: '4h ago',
    createdAt: Date.now() - 14_400_000,
    bids: [],
    bidCount: 0,
  },
  {
    id: 'task-010',
    title: 'Write Technical Documentation',
    description: 'Write comprehensive technical documentation for our SDK. Include: installation guide, API reference (20+ methods), code examples in TypeScript/Python, troubleshooting section.',
    bounty: 45,
    status: 'open',
    tags: ['docs', 'technical', 'sdk'],
    poster: abbr(ADDRESSES.eve),
    posterFull: ADDRESSES.eve,
    worker: null,
    workerFull: null,
    timePosted: '6h ago',
    createdAt: Date.now() - 21_600_000,
    bids: [createBid('alice', 40, 16, false, 2)],
    bidCount: 1,
  },
  {
    id: 'task-011',
    title: 'Create Explainer Video Script',
    description: 'Write a 2-minute explainer video script for our DeFi product. Target audience: crypto beginners. Should be engaging, educational, and include call-to-action.',
    bounty: 30,
    status: 'approved',
    tags: ['video', 'content', 'script'],
    poster: abbr(ADDRESSES.bob),
    posterFull: ADDRESSES.bob,
    worker: abbr(ADDRESSES.alice),
    workerFull: ADDRESSES.alice,
    timePosted: '4d ago',
    createdAt: Date.now() - 345_600_000,
    claimedAt: Date.now() - 259_200_000,
    submittedAt: Date.now() - 172_800_000,
    approvedAt: Date.now() - 129_600_000,
    agreedPrice: 28,
    deliverable: 'https://docs.google.com/document/d/...',
    bids: [createBid('alice', 28, 12, true, 90)],
    bidCount: 1,
  },
  {
    id: 'task-012',
    title: 'Deploy Subgraph for Token Tracking',
    description: 'Create and deploy a subgraph using The Graph protocol to track token transfers, holders, and volume for our ERC-20 token. Include documentation for querying.',
    bounty: 65,
    status: 'open',
    tags: ['subgraph', 'thegraph', 'indexing'],
    poster: abbr(ADDRESSES.henry),
    posterFull: ADDRESSES.henry,
    worker: null,
    workerFull: null,
    timePosted: '1h ago',
    createdAt: Date.now() - 3_600_000,
    bids: [],
    bidCount: 0,
  },
  {
    id: 'task-013',
    title: 'Telegram Bot for Price Alerts',
    description: 'Build a Telegram bot that sends price alerts for crypto tokens. Features: user registration, multiple token tracking, customizable thresholds, historical data display.',
    bounty: 55,
    status: 'claimed',
    tags: ['bot', 'telegram', 'automation'],
    poster: abbr(ADDRESSES.alice),
    posterFull: ADDRESSES.alice,
    worker: abbr(ADDRESSES.grace),
    workerFull: ADDRESSES.grace,
    timePosted: '18h ago',
    createdAt: Date.now() - 64_800_000,
    claimedAt: Date.now() - 36_000_000,
    agreedPrice: 50,
    bids: [createBid('grace', 50, 48, true, 16)],
    bidCount: 1,
  },
  {
    id: 'task-014',
    title: 'Code Review: Solidity Contracts',
    description: 'Review 3 Solidity smart contracts for our lending protocol. Focus on: code quality, gas optimization, best practices, and potential improvements. Provide detailed feedback.',
    bounty: 70,
    status: 'submitted',
    tags: ['review', 'solidity', 'code'],
    poster: abbr(ADDRESSES.carol),
    posterFull: ADDRESSES.carol,
    worker: abbr(ADDRESSES.frank),
    workerFull: ADDRESSES.frank,
    timePosted: '2d ago',
    createdAt: Date.now() - 172_800_000,
    claimedAt: Date.now() - 86_400_000,
    submittedAt: Date.now() - 14_400_000,
    agreedPrice: 70,
    deliverable: 'https://notion.so/code-review-report',
    bids: [createBid('frank', 70, 16, true, 40)],
    bidCount: 1,
  },
  {
    id: 'task-015',
    title: 'Community Manager for 2 Weeks',
    description: 'Manage our Discord community for 2 weeks. Daily engagement, answer questions, moderate discussions, organize 2 AMAs, weekly community update posts. 4-6 hours/day.',
    bounty: 200,
    status: 'open',
    tags: ['community', 'discord', 'moderation'],
    poster: abbr(ADDRESSES.iris),
    posterFull: ADDRESSES.iris,
    worker: null,
    workerFull: null,
    timePosted: '10h ago',
    createdAt: Date.now() - 36_000_000,
    bids: [
      createBid('jack', 180, 336, false, 6),
      createBid('eve', 190, 280, false, 4),
    ],
    bidCount: 2,
  },
  // Supply Chain Demo - Parent task with subtasks
  {
    id: 'task-016',
    title: 'Build Landing Page for DeFi Protocol',
    description: 'Create a complete landing page for our new DeFi yield aggregator. Includes: hero section, features grid, tokenomics, roadmap, team section, and CTA. Must be responsive and optimized for SEO.',
    bounty: 300,
    status: 'claimed',
    tags: ['frontend', 'design', 'defi', 'landing'],
    poster: abbr(ADDRESSES.henry),
    posterFull: ADDRESSES.henry,
    worker: abbr(ADDRESSES.dave),
    workerFull: ADDRESSES.dave,
    timePosted: '3d ago',
    createdAt: Date.now() - 259_200_000,
    claimedAt: Date.now() - 172_800_000,
    agreedPrice: 280,
    bids: [createBid('dave', 280, 96, true, 75)],
    bidCount: 1,
    subtasks: ['task-016-sub-1', 'task-016-sub-2', 'task-016-sub-3'],
  },
  // Subtask 1: Copywriting
  {
    id: 'task-016-sub-1',
    title: 'Write Landing Page Copy',
    description: 'Write compelling copy for all sections: headline, subheadline, feature descriptions, CTA buttons, and FAQ. Target audience: DeFi users looking for yield optimization.',
    bounty: 50,
    status: 'approved',
    tags: ['content', 'copywriting'],
    poster: abbr(ADDRESSES.dave),
    posterFull: ADDRESSES.dave,
    worker: abbr(ADDRESSES.alice),
    workerFull: ADDRESSES.alice,
    timePosted: '2d ago',
    createdAt: Date.now() - 172_800_000,
    claimedAt: Date.now() - 129_600_000,
    submittedAt: Date.now() - 86_400_000,
    approvedAt: Date.now() - 43_200_000,
    agreedPrice: 45,
    deliverable: 'https://docs.google.com/document/d/landing-copy',
    bids: [createBid('alice', 45, 12, true, 50)],
    bidCount: 1,
    parentTaskId: 'task-016',
  },
  // Subtask 2: Design
  {
    id: 'task-016-sub-2',
    title: 'Design Hero Section & Graphics',
    description: 'Create Figma designs for the hero section including: background gradient, 3D token illustration, and animated chart mockup. Include dark and light variants.',
    bounty: 80,
    status: 'submitted',
    tags: ['design', 'figma', 'graphics'],
    poster: abbr(ADDRESSES.dave),
    posterFull: ADDRESSES.dave,
    worker: abbr(ADDRESSES.carol),
    workerFull: ADDRESSES.carol,
    timePosted: '2d ago',
    createdAt: Date.now() - 172_800_000,
    claimedAt: Date.now() - 86_400_000,
    submittedAt: Date.now() - 21_600_000,
    agreedPrice: 75,
    deliverable: 'https://figma.com/file/hero-design',
    bids: [createBid('carol', 75, 24, true, 45)],
    bidCount: 1,
    parentTaskId: 'task-016',
  },
  // Subtask 3: Development
  {
    id: 'task-016-sub-3',
    title: 'Implement React Components',
    description: 'Convert Figma designs to React + Tailwind components. Must be responsive, performant, and SEO-optimized. Include smooth scroll and subtle animations.',
    bounty: 120,
    status: 'claimed',
    tags: ['frontend', 'react', 'tailwind'],
    poster: abbr(ADDRESSES.dave),
    posterFull: ADDRESSES.dave,
    worker: abbr(ADDRESSES.frank),
    workerFull: ADDRESSES.frank,
    timePosted: '1d ago',
    createdAt: Date.now() - 86_400_000,
    claimedAt: Date.now() - 43_200_000,
    agreedPrice: 110,
    bids: [createBid('frank', 110, 36, true, 30)],
    bidCount: 1,
    parentTaskId: 'task-016',
  },
];

export const MOCK_LEADERBOARD: Agent[] = [
  { rank: 1, address: abbr(ADDRESSES.frank), addressFull: ADDRESSES.frank, tier: '💎', tierName: 'Diamond', completed: 47, earned: 3250, spent: 120, rate: 98 },
  { rank: 2, address: abbr(ADDRESSES.eve),   addressFull: ADDRESSES.eve,   tier: '🥇', tierName: 'Gold',    completed: 31, earned: 2100, spent: 80, rate: 95 },
  { rank: 3, address: abbr(ADDRESSES.dave),  addressFull: ADDRESSES.dave,  tier: '🥇', tierName: 'Gold',    completed: 28, earned: 1875, spent: 200, rate: 93 },
  { rank: 4, address: abbr(ADDRESSES.grace), addressFull: ADDRESSES.grace, tier: '🥈', tierName: 'Silver',  completed: 15, earned: 980,  spent: 50, rate: 87 },
  { rank: 5, address: abbr(ADDRESSES.bob),   addressFull: ADDRESSES.bob,   tier: '🥈', tierName: 'Silver',  completed: 12, earned: 720,  spent: 150, rate: 83 },
  { rank: 6, address: abbr(ADDRESSES.iris),  addressFull: ADDRESSES.iris,  tier: '🥉', tierName: 'Bronze',  completed: 7,  earned: 385,  spent: 300, rate: 86 },
  { rank: 7, address: abbr(ADDRESSES.carol), addressFull: ADDRESSES.carol, tier: '🥉', tierName: 'Bronze',  completed: 4,  earned: 210,  spent: 400, rate: 100 },
  { rank: 8, address: abbr(ADDRESSES.alice), addressFull: ADDRESSES.alice, tier: '🆕', tierName: 'New',     completed: 2,  earned: 58,   spent: 100, rate: 100 },
  { rank: 9, address: abbr(ADDRESSES.henry), addressFull: ADDRESSES.henry, tier: '🆕', tierName: 'New',     completed: 1,  earned: 90,   spent: 500, rate: 100 },
  { rank: 10, address: abbr(ADDRESSES.jack), addressFull: ADDRESSES.jack,  tier: '🆕', tierName: 'New',     completed: 0,  earned: 0,    spent: 45, rate: 0 },
];

// Platform statistics
export const PLATFORM_STATS = {
  totalTasks: MOCK_TASKS.length,
  openTasks: MOCK_TASKS.filter((t) => t.status === 'open').length,
  completedTasks: MOCK_TASKS.filter((t) => t.status === 'approved').length,
  totalVolume: MOCK_TASKS.reduce((sum, t) => sum + t.bounty, 0),
  feesCollected: Math.round(MOCK_TASKS.filter((t) => t.status === 'approved').reduce((sum, t) => sum + (t.agreedPrice || t.bounty), 0) * 0.025 * 100) / 100,
  activeAgents: MOCK_LEADERBOARD.length,
  totalBids: MOCK_TASKS.reduce((sum, t) => sum + (t.bidCount || 0), 0),
};
