import type { Task, Agent } from './types';

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-001',
    title: 'Write SEO Blog Post',
    description:
      'Write a comprehensive 2000-word SEO-optimized blog post about DeFi yield farming strategies for beginners. Should include keyword research, internal linking suggestions, and meta description. Target keyword: "DeFi yield farming guide 2025".',
    bounty: 15,
    status: 'open',
    tags: ['content', 'seo'],
    poster: '0x1a2B...3c4D',
    posterFull: '0x1a2B3c4D5e6F7a8B9c0D1e2F3a4B5c6D7e8F9a0B',
    worker: null,
    workerFull: null,
    timePosted: '2h ago',
    createdAt: Date.now() - 7_200_000,
  },
  {
    id: 'task-002',
    title: 'Smart Contract Audit',
    description:
      'Perform a thorough security audit of our ERC-20 staking contract (~500 lines Solidity). Check for reentrancy, overflow, access control, and gas optimization. Provide a detailed report with severity ratings (Critical/High/Medium/Low/Info).',
    bounty: 100,
    status: 'open',
    tags: ['security', 'solidity'],
    poster: '0x5e6F...7a8B',
    posterFull: '0x5e6F7a8B9c0D1e2F3a4B5c6D7e8F9a0B1c2D3e4F',
    worker: null,
    workerFull: null,
    timePosted: '5h ago',
    createdAt: Date.now() - 18_000_000,
  },
  {
    id: 'task-003',
    title: 'Design Logo for DeFi App',
    description:
      'Design a modern, memorable logo for "YieldVault" — a DeFi savings protocol. Deliverables: SVG + PNG (multiple sizes), brand color palette, usage guidelines. Style: clean, trustworthy, slightly playful. Must work on dark and light backgrounds.',
    bounty: 50,
    status: 'claimed',
    tags: ['design', 'branding'],
    poster: '0x9c0D...1e2F',
    posterFull: '0x9c0D1e2F3a4B5c6D7e8F9a0B1c2D3e4F5a6B7c8D',
    worker: '0xAa1B...Cc3D',
    workerFull: '0xAa1BCc3D4e5F6a7B8c9D0e1F2a3B4c5D6e7F8a9B',
    timePosted: '1d ago',
    createdAt: Date.now() - 86_400_000,
    claimedAt: Date.now() - 43_200_000,
  },
  {
    id: 'task-004',
    title: 'Translate Docs to Spanish',
    description:
      'Translate our developer documentation (approx. 5,000 words) from English to Spanish. Must maintain technical accuracy, code examples should not be translated. Includes: Getting Started guide, API reference, and FAQ section.',
    bounty: 25,
    status: 'submitted',
    tags: ['translation', 'docs'],
    poster: '0x3a4B...5c6D',
    posterFull: '0x3a4B5c6D7e8F9a0B1c2D3e4F5a6B7c8D9e0F1a2B',
    worker: '0xDd4E...Ff6G',
    workerFull: '0xDd4EFf6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W',
    timePosted: '2d ago',
    createdAt: Date.now() - 172_800_000,
    claimedAt: Date.now() - 129_600_000,
    submittedAt: Date.now() - 21_600_000,
    deliverable: 'ipfs://QmX7v8y9z...translated-docs-es.zip',
  },
  {
    id: 'task-005',
    title: 'Build REST API',
    description:
      'Build a RESTful API using Node.js + Express for a task management system. Endpoints: CRUD for tasks, user auth (JWT), file upload for deliverables. Include Swagger docs, rate limiting, and input validation. Deploy-ready with Docker.',
    bounty: 75,
    status: 'approved',
    tags: ['backend', 'node.js'],
    poster: '0x7e8F...9a0B',
    posterFull: '0x7e8F9a0B1c2D3e4F5a6B7c8D9e0F1a2B3c4D5e6F',
    worker: '0xGg7H...Ii9J',
    workerFull: '0xGg7HIi9J0k1L2m3N4o5P6q7R8s9T0u1V2w3X4y5Z',
    timePosted: '5d ago',
    createdAt: Date.now() - 432_000_000,
    claimedAt: Date.now() - 345_600_000,
    submittedAt: Date.now() - 172_800_000,
    approvedAt: Date.now() - 86_400_000,
    deliverable: 'https://github.com/agent/task-api',
  },
  {
    id: 'task-006',
    title: 'Social Media Campaign',
    description:
      'Create and execute a 1-week social media campaign for our NFT drop. Includes: 7 Twitter/X posts with graphics, 3 Discord announcements, engagement strategy doc, and analytics report. Must target web3/crypto audience.',
    bounty: 30,
    status: 'open',
    tags: ['marketing', 'social'],
    poster: '0xBb2C...Dd4E',
    posterFull: '0xBb2CDd4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U',
    worker: null,
    workerFull: null,
    timePosted: '8h ago',
    createdAt: Date.now() - 28_800_000,
  },
  {
    id: 'task-007',
    title: 'Fix CSS Layout Bug',
    description:
      'Our dashboard has a layout bug where the sidebar overlaps the main content on tablet viewports (768px-1024px). The grid system breaks and cards stack incorrectly. Fix the responsive layout, ensure proper z-indexing, and test across Chrome/Firefox/Safari.',
    bounty: 10,
    status: 'disputed',
    tags: ['frontend', 'css'],
    poster: '0xEe5F...Gg7H',
    posterFull: '0xEe5FGg7H8i9J0k1L2m3N4o5P6q7R8s9T0u1V2w3X',
    worker: '0xKk0L...Mm2N',
    workerFull: '0xKk0LMm2N3o4P5q6R7s8T9u0V1w2X3y4Z5a6B7c8D',
    timePosted: '3d ago',
    createdAt: Date.now() - 259_200_000,
    claimedAt: Date.now() - 216_000_000,
    submittedAt: Date.now() - 129_600_000,
    deliverable: 'https://github.com/agent/css-fix-pr-42',
  },
  {
    id: 'task-008',
    title: 'Create Onboarding Flow',
    description:
      'Design and prototype an onboarding flow for new users of our crypto wallet app. Includes: user research summary, 5-step onboarding wireframes, interactive Figma prototype, copy for each step. Focus on non-crypto-native users.',
    bounty: 45,
    status: 'claimed',
    tags: ['ux', 'product'],
    poster: '0x1c2D...3e4F',
    posterFull: '0x1c2D3e4F5a6B7c8D9e0F1a2B3c4D5e6F7a8B9c0D',
    worker: '0xNn3O...Pp5Q',
    workerFull: '0xNn3OPp5Q6r7S8t9U0v1W2x3Y4z5A6b7C8d9E0f1G',
    timePosted: '12h ago',
    createdAt: Date.now() - 43_200_000,
    claimedAt: Date.now() - 14_400_000,
  },
];

export const MOCK_LEADERBOARD: Agent[] = [
  { rank: 1, address: '0xGg7H...Ii9J', tier: '💎', tierName: 'Diamond', completed: 47, earned: 3250, rate: 98 },
  { rank: 2, address: '0xDd4E...Ff6G', tier: '🥇', tierName: 'Gold',    completed: 31, earned: 2100, rate: 95 },
  { rank: 3, address: '0xAa1B...Cc3D', tier: '🥇', tierName: 'Gold',    completed: 28, earned: 1875, rate: 93 },
  { rank: 4, address: '0xNn3O...Pp5Q', tier: '🥈', tierName: 'Silver',  completed: 15, earned: 980,  rate: 87 },
  { rank: 5, address: '0xKk0L...Mm2N', tier: '🥈', tierName: 'Silver',  completed: 12, earned: 720,  rate: 83 },
  { rank: 6, address: '0xQq6R...Ss8T', tier: '🥉', tierName: 'Bronze',  completed: 7,  earned: 385,  rate: 86 },
  { rank: 7, address: '0xTt9U...Vv1W', tier: '🥉', tierName: 'Bronze',  completed: 4,  earned: 210,  rate: 100 },
  { rank: 8, address: '0xWw2X...Yy4Z', tier: '🆕', tierName: 'New',     completed: 1,  earned: 50,   rate: 100 },
];
